### PR TITLE
Changes content header for JSON-LD mimetype.

### LINKED ISSUE #275: Change mime type for JSON-LD
Currently the hydra-head generator sets the mimetype to 'application/json', but it should be 'application/ld+json'.

The effect is that controllers don't know how to respond to JSON-LD requests.

### PR DESCRIPTION
**Pull request by afred**
Closes #275.

### CODE REVIEW

**Comment by afred** [comment]
I changed the content types for JOSN-LD mimetypes from `application/json` to
`application/ld+json` and ran the tests.. and the tests passed. But I didn't
think the tests were covering the situation that caused me to bump into this
issue in the first place -- which was in the context of a Sufia 6.2.0 app that
had a `respond_to` block, responding to individual formats.

So I monkey patched `CatalogController` just to see if I could replicate the
error I was running into, and I was able to do that. (I can make the test prettier once it's passing).

I went ahead and submitted the PR just to get some eyes on it. I need help figuring out:
  1. Am I right to be testing content negotiation with a custom `respond_to` block?
  1. If so, what else am I missing here?

**Comment by afred** [comment]
@terrellt @jcoyne ^^

**Comment by mjgiarlo** [comment]
:+1:

**Comment by terrellt** [comment]
I'm not sure this needs a test, since it's making the mime type right. I'm inclined to just merge it.

**Comment by mjgiarlo** [comment]
I'm good with that, @terrellt

**Comment by terrellt** [comment]
Hydra-tech call just says add a check to the existing specs to make sure the mime type is what we expect, and then we can merge.

**Comment by mjgiarlo** [comment]
Discussed on today's Hydra Tech call.  This change should probably have broken a spec, but it didn't because we're not checking response MIME types. Add a test and then merge ASAP so this can be in the next release.

**Comment by mjgiarlo** [comment]
:hand: (let's say that's a high-five emoji), @terrellt

**Comment by terrellt** [comment]
:hand:

**Pull request merged**
