### PR TITLE
Upgrade Blacklight to 5.10

### PR DESCRIPTION
**Pull request by cjcolvar**
Backport of changes made in the Hydra-head 9.1 release.

### CODE REVIEW

**Comment by awead** [comment]
:+1: if Travis is :green_heart:

**Comment by dchandekstark** [comment]
@cjcolvar Do these changes preserve backward compatibility? I see some method signatures have been changed.

**Comment by jcoyne** [comment]
@dchandekstark That method is called by blacklight, and blacklight has changed how it will be called, so I don't see a backward compatibility issue.

**Comment by dchandekstark** [comment]
@jcoyne OK, right, since this change forces the BL upgrade.

**Comment by cjcolvar** [comment]
@jcoyne @awead @dchandekstark Is there anything else that should be done on this or is it good to merge now that the build has passed?

**Pull request merged**
