### PR TITLE
Update to work with Fedora 4 pids and the Hydra-head 9.1 API

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Looks :ok: to me.  :+1:

**Comment by awead** [comment]
Other than the minor change I noted, looks good to me.

**Comment by jcoyne** [comment]
@awead that minor change is fixed in 9cfc071, right?

**Comment by awead** [comment]
@jcoyne yes. Didn't see that. Unless you want to squash anything, I'm okay with merging.

**Comment by jcoyne** [comment]
@awead I don't particularly want to squash as these are all distinct changes.

**Pull request merged**
