### PR TITLE
Action view fix

### PR DESCRIPTION
**Pull request by dchandekstark**
I'm not sure this is the best place to fix https://github.com/haml/haml/issues/695.

### CODE REVIEW

**Comment by jcoyne** [comment]
Why are we using haml? That's not in the gemspec is it?

**Comment by dchandekstark** [comment]
ruby-rdf?

	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/haml-4.0.7/lib/haml/helpers/safe_erubis_template.rb:1:in `<top (required)>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/haml-4.0.7/lib/haml/railtie.rb:21:in `<top (required)>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/haml-4.0.7/lib/haml.rb:23:in `<top (required)>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/rdf-rdfa-1.99.1/lib/rdf/rdfa/writer.rb:1:in `<top (required)>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/rdf-rdfxml-1.99.0/lib/rdf/rdfxml/writer.rb:50:in `<module:RDFXML>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/rdf-rdfxml-1.99.0/lib/rdf/rdfxml/writer.rb:3:in `<top (required)>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/active-fedora-8.4.0/lib/active_fedora/rdf_xml_writer.rb:8:in `<module:ActiveFedora>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/active-fedora-8.4.0/lib/active_fedora/rdf_xml_writer.rb:3:in `<top (required)>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/active-fedora-8.4.0/lib/active_fedora/rels_ext_datastream.rb:3:in `<top (required)>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/active-fedora-8.4.0/lib/active_fedora/datastreams.rb:9:in `block in <module:Datastreams>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/activesupport-4.2.7.1/lib/active_support/concern.rb:120:in `class_eval'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/activesupport-4.2.7.1/lib/active_support/concern.rb:120:in `append_features'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/active-fedora-8.4.0/lib/active_fedora/base.rb:37:in `include'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/active-fedora-8.4.0/lib/active_fedora/base.rb:37:in `<class:Base>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/active-fedora-8.4.0/lib/active_fedora/base.rb:26:in `<module:ActiveFedora>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/active-fedora-8.4.0/lib/active_fedora/base.rb:6:in `<top (required)>'
	from /Users/dc/github/projecthydra/hydra-head/hydra-access-controls/spec/support/mods_asset.rb:1:in `<top (required)>'
	from /Users/dc/github/projecthydra/hydra-head/hydra-access-controls/spec/spec_helper.rb:35:in `<top (required)>'
	from /Users/dc/github/projecthydra/hydra-head/hydra-access-controls/spec/services/embargo_service_spec.rb:1:in `require'
	from /Users/dc/github/projecthydra/hydra-head/hydra-access-controls/spec/services/embargo_service_spec.rb:1:in `<top (required)>'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/dc/.rvm/gems/ruby-2.3.1@hydra-head/gems/rspec-core-3.5.4/exe/rspec:4:in `<main>'

**Comment by dchandekstark** [comment]
Going to also take this opportunity to drop Rails 4.0 and Ruby 2.0.0.

**Comment by jcoyne** [comment]
@no-reply can you take a look at that haml/rdf issue?  Does the fix belong upstream?

**Comment by dchandekstark** [comment]
I closed the PR b/c forgot to push an extra commit to 8-2-stable first.

**Pull request closed without merging**
