### PR TITLE
[WIP] Make Hydra's web ACLs look like Fedora web ACLs -- DON'T MERGE

### PR DESCRIPTION
**Pull request by jcoyne**
**DON'T MERGE**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Looks great! :shipit:

**Comment by tpendragon** [comment]
Running this through Plum's test suite and checking to see if Fedora's understanding it all.

**Comment by tpendragon** [comment]
Read groups don't seem to be persisting with this...maybe I'm doing something wrong?

**Comment by tpendragon** [comment]
Yup, the ACLs on the access_control don't persist automatically.

**Comment by tpendragon** [comment]
```
[16] pry(main)> class Bla < ActiveFedora::Base
[16] pry(main)*   include Hydra::AccessControls::Permissions
[16] pry(main)* end
=> Bla
[17] pry(main)> b = Bla.new
=> #<Bla id: nil, access_control_id: nil>
[18] pry(main)> b.read_groups = ['banana']
=> ["banana"]
[19] pry(main)> b.read_groups
=> ["banana"]
[20] pry(main)> b.save
=> true
[21] pry(main)> b.read_groups
=> ["banana"]
[22] pry(main)> b.reload
=> #<Bla id: "0e35b303-18e2-40c6-879c-91a8ff891fae", access_control_id: "9eed75d4-5820-4b70-9a54-105331e1d926">
[23] pry(main)> b.read_groups
=> []
[24] pry(main)> b.access_control.acls
=> []
[25] pry(main)>
```

**Comment by jcoyne** [comment]
Yes, this is using direct_containment, and we need to use basic containment :(. Unfortunately, ActiveFedora doesn't have basic containment implemented in a sane way.

**Pull request closed without merging**
