### PR TITLE
hydra-head v8.0.0.rc1

### PR DESCRIPTION
**Pull request by dchandekstark**
Upgraded active-fedora to ~> 8.0.0
Removed deprecated code
Pinned jettywrapper to 1.x

### CODE REVIEW

**Comment by dchandekstark** [comment]
Rails 3 builds fail on Travis due to odd bundler dependency resolution:
```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    activemodel (~> 3.2.13) ruby depends on
      activesupport (= 3.2.13) ruby
    hydra-head (>= 0) ruby depends on
      hydra-access-controls (= 8.0.0.rc1) ruby depends on
        active-fedora (~> 8.0.0) ruby depends on
          activesupport (3.0.0)
```

**Comment by dchandekstark** [comment]
Dropped support for Rails 3
Added rvm 2.2 in Travis config
Gemfiles for Rails 4.0, 4.1, and 4.2 in Travis config

**Comment by dchandekstark** [comment]
@jcoyne @cam156 All tests are passing after dropping Rails 3.  I added ruby 2.2 and gemfiles for Rails 4.0, 4.1, and 4.2.  Possibly overkill, but there it is.  Anyone else need to weigh in? @jeremyf @mjgiarlo @awead

**Comment by awead** [comment]
I think it's reasonable to not *support* Rails 3. We're not saying you can't use it, but you probably wouldn't want to anyway, so :+1:

**Comment by dchandekstark** [comment]
@awead Well, actually, as modified the gem *requires* Rails 4. I suppose I could roll that back and just leave Rails 3 *untested* ... ?

**Comment by awead** [comment]
@dchandekstark  even better!

**Comment by dchandekstark** [comment]
OK, can I get a merge then? @jcoyne @cam156 @awead

**Pull request merged**
