### PR TITLE
Blacklight 6

### PR DESCRIPTION
**Pull request by jcoyne**
Wait on a release of BL 6 before merging.

### CODE REVIEW

**Comment by cam156** [comment]
@jcoyne This looks like it should be two commits instead of 3.

**Comment by jcoyne** [comment]
@cam156 yeah, it will be rebased before it's ready for merge.

**Comment by cam156** [comment]
@jcoyne cool. I'm testing with it now and it seems to be working.

**Comment by jcoyne** [comment]
Replaced by 309

**Pull request closed without merging**
