### PR TITLE
Log all LDP HTTP API traffic in debug mode

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by jcoyne** [comment]
Please don't merge this yet. I think it may go better in AF

**Comment by grosscol** [comment]
Would this basically replace the use of http-logger for debugging in development?

**Comment by jcoyne** [comment]
@grosscol no, this basically restores the behavior we had in ldp 0.3.0 where all the requests were logged.

**Comment by mjgiarlo** [comment]
@jcoyne This PR still relevant and needed?

**Pull request closed without merging**
